### ISSUE TITLE
SharkserverBuyer does not work

### ISSUE THREAD

**Issue by i-am-xhy** [Skynet2-0/Skynet2.0#52]
>>> ssb.buy()
Could not complete the transaction because an error occurred:
'SharkserversBuyer' object has no attribute 'clickSelectElement'
False

**Comment by i-am-xhy** [comment]
additionally in requirements.txt one of teh new requirements has only one = instead of 2

**Comment by Robdeprop** [comment]
Thanks, this has been fixed
